external_components:
  - source: github://HarmEllis/esphome-cc1101@main
    components: [ cc1101 ]
  - source: github://HarmEllis/esphome-somfy-cover-remote@main
    components: [ somfy_cover ]

esphome:
  name: pool_light
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Wi-Fi
wifi:
  ssid: "Your_SSID"
  password: "Your_PASSWORD"

# Enable Web Server
web_server:
  port: 80

# CC1101 Configuration
cc1101:
  id: cc1101_module
  cs_pin: GPIO5
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  reset_pin: GPIO4
  frequency: 433.42 MHz

# Button configuration to control pool light
button:
  - platform: pool_light
    id: pool_light_power
    name: "Pool Light Power"
    id0: 249
    id1: 203
    instruction: power
    mode: poolandspa
    cc1101_module: cc1101_module
