external_components:
  - source: github://HarmEllis/esphome-cc1101@main
    components: [ cc1101 ]
  - source: github://HarmEllis/esphome-somfy-cover-remote@main
    components: [ somfy_cover ]

esphome:
  name: pool_light
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Wi-Fi
wifi:
  ssid: "Your_SSID"
  password: "Your_PASSWORD"

# Enable Web Server
web_server:
  port: 80

cc1101:
  id: "cc1101_module"
  cc1101_frequency: 433.42
  mosi_pin: 6
  miso_pin: 5
  clk_pin: 4
  cs_pin: 7
  cc1101_emitter_pin: 3

# Button configuration to control pool light
button:
  - platform: pool_light
    id: pool_light_power
    name: "Pool Light Power"
    id0: 249
    id1: 203
    instruction: power
    mode: poolandspa
    cc1101_module: cc1101_module
